ingredients_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('manage_ingredients.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manage_ingredients/urls.py
from django.urls import path
from . import views


app_name = 'manage_ingredients'
urlpatterns = [
    path('', views.main, name='main'),
    path('ingredients/', views.ingredients_list, name='ingredients_list'),
    path('ingredients/<int:ingredient_id>', views.owned_ingredients, name='owned_ingredients'),
    path('ingredients/<int:ingredient_id>/add_owned_ingredient', views.add_owned_ingredient,
         {'redirect_url': 'manage_ingredients:owned_ingredients',
          'url_name': 'manage_ingredients:add_owned_ingredient_id'}, name='add_owned_ingredient_id'),
    path('recipes/', views.recipes_list, name='recipes'),
    path('use_up_today/', views.use_up_today_list, name='use_up_today'),
    path('add_ingredient/', views.add_ingredient, name='add_ingredient'),
    path('edit_ingredient/<int:ingredient_id>/', views.edit_ingredient, name='edit_ingredient'),
    path('delete_ingredient/<int:ingredient_id>/', views.delete_ingredient, name='delete_ingredient'),
    path('add_owned_ingredient/<int:ingredient_id>', views.add_owned_ingredient,
         {'redirect_url': 'manage_ingredients:ingredients_list', 'url_name': 'manage_ingredients:add_owned_ingredient'},
         name='add_owned_ingredient'),
    path('edit_owned_ingredient/<int:owned_ingredient_id>/', views.edit_owned_ingredient,
         {'redirect_url': 'manage_ingredients:owned_ingredients', 'url_name': 'manage_ingredients:edit_owned_ingredient'},
         name='edit_owned_ingredient'),
    path('delete_owned_ingredient/<int:owned_ingredient_id>/', views.delete_owned_ingredient,
         {'redirect_url': 'manage_ingredients:owned_ingredients', 'url_name': 'manage_ingredients:owned_ingredients'},
         name='delete_owned_ingredient'),
    path('use_up_today/edit_owned_ingredient/<int:owned_ingredient_id>/', views.edit_owned_ingredient,
         {'redirect_url': 'manage_ingredients:use_up_today', 'url_name': 'manage_ingredients:edit_owned_ingredient_use_up'},
         name='edit_owned_ingredient_use_up'),
    path('use_up_today/delete_owned_ingredient/<int:owned_ingredient_id>/', views.delete_owned_ingredient,
         {'redirect_url': 'manage_ingredients:use_up_today', 'url_name': 'manage_ingredients:use_up_today'},
         name='delete_owned_ingredient_use_up'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('edit_recipe/<int:recipe_id>/', views.edit_recipe, name='edit_recipe'),
    path('delete_recipe/<int:recipe_id>/', views.delete_recipe, name='delete_recipe'),
    path('get_recipes/<int:ingredient_id>/', views.get_recipes, name='get_recipes'),
    path('manage_categories/', views.manage_categories, name='manage_categories'),
    path('categories/', views.categories_list, name='categories_list'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

manage_ingredients/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=32)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'categories'

        constraints = [
            models.UniqueConstraint(fields=['name', 'owner_id'], name='unique_name_category'),
        ]

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    UNIT = [
        ('ML', 'ml'),
        ('G', 'g'),
        ('PCS', 'pcs.'),
    ]
    name = models.CharField(max_length=32)
    unit = models.CharField(max_length=5, choices=UNIT)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'owner_id'], name='unique_name_ingredient'),
        ]

    def __str__(self):
        return self.name


class OwnedIngredient(models.Model):
    note = models.CharField(max_length=16, default='...')
    quantity = models.FloatField(default=0)
    best_before = models.DateField()
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


class Recipe(models.Model):
    title = models.CharField(max_length=32)
    link = models.URLField(max_length=200)
    ingredient = models.ManyToManyField(Ingredient, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['title', 'owner_id'], name='unique_name_recipe'),
        ]

    def __str__(self):
        return self.title

manage_ingredients/forms.py
from django import forms
from .models import Ingredient, OwnedIngredient, Category, Recipe


class DateInput(forms.DateInput):
    input_type = 'date'


class AddIngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name', 'unit', 'category']


class EditIngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name', 'unit', 'category']


class AddOwnedIngredientForm(forms.ModelForm):
    class Meta:
        model = OwnedIngredient
        fields = ['quantity', 'best_before', 'note']
        widgets = {
            'best_before': DateInput()
        }


class EditOwnedIngredientForm(forms.ModelForm):
    class Meta:
        model = OwnedIngredient
        fields = ['quantity', 'best_before', 'note']
        widgets = {
            'best_before': DateInput()
        }


class AddRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'link', 'ingredient']
        widgets = {
            'ingredient': forms.CheckboxSelectMultiple()
        }


class EditRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'link', 'ingredient']
        widgets = {
            'ingredient': forms.CheckboxSelectMultiple()
        }


class ManageCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {'name': 'Edit/Add category'}
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Add new category'})
        }

manage_ingredients/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.db import IntegrityError
from django.db.models import Sum
from datetime import date, timedelta
from django.forms import modelformset_factory
from .models import Category, Recipe, Ingredient, OwnedIngredient
from .forms import AddIngredientForm, EditIngredientForm, AddOwnedIngredientForm, EditOwnedIngredientForm,\
    AddRecipeForm, EditRecipeForm, ManageCategoryForm
from .filters import IngredientFilter, RecipeFilter


def check_owner(owner, user):
    if owner != user:
        raise Http404


def main(request):
    return render(request, 'manage_ingredients/main.html')


@login_required
def ingredients_list(request):
    ingredients = Ingredient.objects.filter(owner=request.user).annotate(total=Sum('ownedingredient__quantity'))

    ingredient_filter = IngredientFilter(request.GET, request=request, queryset=ingredients)
    ingredients = ingredient_filter.qs

    context = {'ingredients': ingredients, 'filter': ingredient_filter}
    return render(request, 'manage_ingredients/ingredients_list.html', context)


@login_required
def owned_ingredients(request, ingredient_id):
    ingredient = Ingredient.objects.filter(owner=request.user).get(id=ingredient_id)
    owned_ingredient = ingredient.ownedingredient_set.order_by('best_before')

    context = {'ingredient': ingredient, 'owned_ingredient': owned_ingredient}
    return render(request, 'manage_ingredients/owned_ingredient.html', context)


@login_required
def recipes_list(request):
    recipes = Recipe.objects.filter(owner=request.user)

    recipes_filter = RecipeFilter(request.GET, request=request, queryset=recipes)
    recipes = recipes_filter.qs

    context = {'recipes': recipes, 'filter': recipes_filter}
    return render(request, 'manage_ingredients/recipes.html', context)


@login_required
def use_up_today_list(request):
    today = date.today()
    should_use = OwnedIngredient.objects.filter(owner=request.user).filter(quantity__gt=0)\
        .filter(best_before__lte=today + timedelta(days=2), best_before__gte=today)
    passed_date = OwnedIngredient.objects.filter(owner=request.user).filter(quantity__gt=0)\
        .filter(best_before__lte=today)

    context = {'should_use': should_use, 'passed_date': passed_date}
    return render(request, 'manage_ingredients/use_up_today.html', context)


@login_required
def add_ingredient(request):
    e = None
    if request.method != 'POST':
        form = AddIngredientForm()
    else:
        form = AddIngredientForm(data=request.POST)
        if form.is_valid():
            try:
                added_ingredient = form.save(commit=False)
                added_ingredient.owner = request.user
                added_ingredient.save()
                return redirect('manage_ingredients:ingredients_list')
            except IntegrityError:
                e = 'The name must be unique. Ingredient with this name already exists.'

    context = {'form': form, 'url_name': 'manage_ingredients:add_ingredient',
               'url_back': 'manage_ingredients:ingredients_list', 'title': 'Add ingredient', 'e': e}
    return render(request, 'manage_ingredients/add.html', context)


@login_required
def edit_ingredient(request, ingredient_id):
    ingredient = Ingredient.objects.get(id=ingredient_id)
    check_owner(ingredient.owner, request.user)
    if request.method != 'POST':
        form = EditIngredientForm(instance=ingredient)
    else:
        form = EditIngredientForm(instance=ingredient, data=request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('manage_ingredients:ingredients_list')
            except IntegrityError:
                pass

    context = {'object': ingredient, 'form': form, 'url_name': 'manage_ingredients:edit_ingredient',
               'url_cancel': 'manage_ingredients:ingredients_list'}
    return render(request, 'manage_ingredients/edit.html', context)


@login_required
def delete_ingredient(request, ingredient_id):
    ingredient = Ingredient.objects.get(id=ingredient_id)
    check_owner(ingredient.owner, request.user)
    if request.method == 'POST':
        ingredient.delete()
        return redirect('manage_ingredients:ingredients_list')

    context = {'ingredient': ingredient, 'url_name': 'manage_ingredients:ingredients_list', 'name': 'ingredient',
               'field': ingredient.name}
    return render(request, 'manage_ingredients/delete.html', context)


@login_required
def add_owned_ingredient(request, ingredient_id, redirect_url, url_name):
    ingredient = Ingredient.objects.get(id=ingredient_id)
    if request.method != 'POST':
        form = AddOwnedIngredientForm()
    else:
        form = AddOwnedIngredientForm(data=request.POST)
        if form.is_valid():
            added_item = form.save(commit=False)
            added_item.ingredient = ingredient
            added_item.owner = request.user
            added_item.save()
            if redirect_url == 'manage_ingredients:owned_ingredients':
                return redirect(redirect_url, ingredient_id=ingredient_id)
            else:
                return redirect(redirect_url)
    if redirect_url == 'manage_ingredients:owned_ingredients':
        context = {'object': ingredient.id, 'ingredient': ingredient, 'form': form,
                   'url_name': url_name,
                   'url_back': 'manage_ingredients:owned_ingredients', 'object_back': ingredient_id,
                   'title': ingredient.name}
    else:
        context = {'object': ingredient.id, 'ingredient': ingredient, 'form': form,
                   'url_name': url_name,
                   'url_back': 'manage_ingredients:ingredients_list', 'title': ingredient.name}
    return render(request, 'manage_ingredients/add.html', context)


@login_required
def edit_owned_ingredient(request, owned_ingredient_id, redirect_url, url_name):
    owned_ingredient = OwnedIngredient.objects.get(id=owned_ingredient_id)
    ingredient_id = owned_ingredient.ingredient.id
    check_owner(owned_ingredient.owner, request.user)
    if request.method != 'POST':
        form = EditOwnedIngredientForm(instance=owned_ingredient)
    else:
        form = EditOwnedIngredientForm(instance=owned_ingredient, data=request.POST)
        if form.is_valid():
            try:
                form.save()
                if redirect_url == 'manage_ingredients:owned_ingredients':
                    return redirect(redirect_url, ingredient_id=ingredient_id)
                else:
                    return redirect(redirect_url)
            except IntegrityError:
                pass
    if redirect_url == 'manage_ingredients:owned_ingredients':
        context = {'object': owned_ingredient, 'form': form, 'url_name': url_name,
                   'url_cancel': redirect_url, 'object_cancel': ingredient_id}
    else:
        context = {'object': owned_ingredient, 'form': form, 'url_name': url_name,
                   'url_cancel': redirect_url}
    return render(request, 'manage_ingredients/edit.html', context)


@login_required
def delete_owned_ingredient(request, owned_ingredient_id, redirect_url, url_name):
    owned_ingredient = OwnedIngredient.objects.get(id=owned_ingredient_id)
    ingredient_id = owned_ingredient.ingredient.id
    check_owner(owned_ingredient.owner, request.user)
    if request.method == 'POST':
        owned_ingredient.delete()
        if redirect_url == 'manage_ingredients:owned_ingredients':
            return redirect(redirect_url, ingredient_id=ingredient_id)
        else:
            return redirect(redirect_url)
    if redirect_url == 'manage_ingredients:owned_ingredients':
        context = {'ingredient': owned_ingredient, 'url_name': url_name,
                   'object': ingredient_id, 'name': owned_ingredient.ingredient,
                   'field': owned_ingredient.quantity}
    else:
        context = {'ingredient': owned_ingredient, 'url_name': url_name,
                   'name': 'ingredient', 'field': owned_ingredient.quantity}
    return render(request, 'manage_ingredients/delete.html', context)


@login_required
def add_recipe(request):
    e = None
    if request.method != 'POST':
        form = AddRecipeForm()
    else:
        form = AddRecipeForm(data=request.POST)
        if form.is_valid():
            try:
                added_recipe = form.save(commit=False)
                added_recipe.owner = request.user
                added_recipe.save()
                form.save_m2m()
                return redirect('manage_ingredients:recipes')
            except IntegrityError:
                e = 'The name must be unique. Recipe with this name already exists.'

    context = {'form': form, 'url_name': 'manage_ingredients:add_recipe', 'url_back': 'manage_ingredients:recipes',
               'title': 'Add recipe', 'e': e}
    return render(request, 'manage_ingredients/add.html', context)


@login_required
def edit_recipe(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    check_owner(recipe.owner, request.user)
    if request.method != 'POST':
        form = EditRecipeForm(instance=recipe)
    else:
        form = EditRecipeForm(instance=recipe, data=request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('manage_ingredients:recipes')
            except IntegrityError:
                pass

    context = {'object': recipe, 'form': form, 'url_name': 'manage_ingredients:edit_recipe',
               'url_cancel': 'manage_ingredients:recipes'}
    return render(request, 'manage_ingredients/edit.html', context)


@login_required
def delete_recipe(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    check_owner(recipe.owner, request.user)
    if request.method == 'POST':
        recipe.delete()
        return redirect('manage_ingredients:recipes')

manage_ingredients/templates/manage_ingredients/categories_list.html
{% extends 'base.html' %}

{% block page_header %}
  <h1 class="text-center">Be careful! If you delete a category, category items will be deleted too.</h1>
{% endblock page_header %}

{% block content %}

  <a class="btn btn-secondary btn-lg btn-block" href="{% url 'manage_ingredients:manage_categories' %}">Back</a>
  <table class="table mt-4">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Category</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for category in categories %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ category.name }}</td>
          <td><a href="{% url 'manage_ingredients:delete_category' category.id %}">
            <button type="button" class="btn btn-danger">Delete</button></a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}

manage_ingredients/templates/manage_ingredients/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

<form action="." method='post'>
  {% csrf_token %}
    <h3 class="mb-4">Do you want to delete the {{name}}: "{{ field }}"?</h3>
  {% buttons %}
    <input class="btn btn-success" type="submit" value="Yes" />
    {% if object %}
      <a href="{% url url_name object%}"><button type="button" class="btn btn-danger">Cancel</button></a>
    {% else %}
      <a href="{% url url_name %}"><button type="button" class="btn btn-danger">Cancel</button></a>
    {% endif %}
  {% endbuttons %}
</form>

{% endblock content %}

manage_ingredients/templates/manage_ingredients/ingredients_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block page_header %}
  <h2 class="text-center my-3">If you want to know what ingredients you have at any given time, always update your inventory
    after shopping, cooking and cleaning.</h2>
{% endblock page_header %}

{% block content %}

  <a class="btn btn-info mr-5 mt-2" href="{% url 'manage_ingredients:add_ingredient' %}" role="button">
    Add ingredient &raquo;
  </a>
  <a class="btn btn-info mt-2" href="{% url 'manage_ingredients:manage_categories' %}" role="button">
    Manage categories &raquo;
  </a>
  <br>
    <form method="get" class="form-inline mt-4">
      <div class="row">
        {{ filter.form.as_p }}
      </div>
      <button class="btn btn-info ml-5 mt-2" type="submit">Search</button>
    </form>
  <br>
  {% if ingredients %}
  <table class="table table-hover" style="background-color: #f0fafc">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Category</th>
        <th scope="col">Name</th>
        <th scope="col">In Store</th>
        <th scope="col">Unit</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    {% for ingredient in ingredients %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ ingredient.category.name }}</td>
        <td>{{ ingredient.name }}</td>
        <td>
          <a href="{% url 'manage_ingredients:owned_ingredients' ingredient.id %}">
            <button type="button" class="btn btn-light btn-sm mr-2">
              <img src="{% static 'images/pantry.png' %}" width="30" height="26">
            </button>
          </a>
          {{ ingredient.total | floatformat }}
          <a href="{% url 'manage_ingredients:add_owned_ingredient' ingredient.id %}">
            <button type="button" class="btn btn-light btn-sm ml-2">
              <img src="{% static 'images/basket.png' %}" width="14" height="18">
            </button>
          </a>
        </td>
        <td>{{ ingredient.get_unit_display }}</td>
        <td>
          <a href="{% url 'manage_ingredients:get_recipes' ingredient.id%}">
            <button type="button" class="btn btn-light btn-sm">Recipes</button></a>
        </td>
        <td>
          <a href="{% url 'manage_ingredients:edit_ingredient' ingredient.id %}">
            <button type="button" class="btn btn-warning btn-sm">Edit</button></a>
        </td>
        <td>
          <a href="{% url 'manage_ingredients:delete_ingredient' ingredient.id %}">
            <button type="button" class="btn btn-danger btn-sm">Delete</button></a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% else %}
    <h2 class="empty-list-text">It is time to start keeping track of the contents of your pantry and fridge.
      Add ingredients and suitable categories for them.</h2>
  {% endif %}

{% endblock content %}

manage_ingredients/templates/manage_ingredients/main.html
{% extends 'base.html' %}


{% block page_header %}

  <div class='jumbotron mt-4' style="background-color:#dcf2f5;">
    <h1 class="display-4">Cooking Manager</h1>
    <p class="lead">Track your pantry and fridge inventory and store your favorite recipes.</p>
    <hr class="my-4">
      {% if user.is_authenticated %}
        <p>The first steps for reducing your food waste is use up fresh ingredient before it goes bad.</p>
        <a class="btn btn-sm btn-secondary" href="{% url 'manage_ingredients:use_up_today' %}">Use up today &raquo;</a>
        <hr class="my-4">
        <p>Shopping, Organizing And Cleaning</p>
        <p>Keep track of the contents of your pantry and fridge.</p>
        <a class="btn btn-sm btn-secondary" href="{% url 'manage_ingredients:ingredients_list' %}">Keep track &raquo;</a>
        <hr class="my-4">
        <p>What would you like to cook today?</p>
        <a class="btn btn-sm btn-secondary" href="{% url 'manage_ingredients:recipes' %}">Recipes &raquo;</a>
      {% else %}
        <p>Register Your Account. Already Registered? Please log in.</p>
        <a class="btn btn-lg btn-info" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
        <a class="btn btn-lg btn-secondary" href="{% url 'users:login' %}" role="button">Log in &raquo;</a>
        <br>
      {% endif %}
  </div>
{% endblock page_header %}

manage_ingredients/templates/manage_ingredients/manage_categories.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block page_header %}
  <h3>{{ title }}</h3>
  <a class="btn btn-danger" href="{% url 'manage_ingredients:categories_list' %}" role="button">
    Delete categories &raquo;
  </a>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'manage_ingredients:manage_categories' %}" method='post' class="form" >
    {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset %}
      {% bootstrap_form form %}
    {% endfor %}
    <button name="submit" class="btn btn-info">Submit</button>
    <a class="btn btn-sm btn-secondary" href="{% url 'manage_ingredients:ingredients_list' %}">Back</a>
  </form>

{% endblock content %}

manage_ingredients/templates/manage_ingredients/owned_ingredient.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}
  <h1 class="text-center my-3">{{ ingredient.name }}
    <a href="{% url 'manage_ingredients:add_owned_ingredient_id' ingredient.id%}">
      <button type="button" class="btn btn-light btn-sm">
        <img src="{% static 'images/basket.png' %}" width="25" height="30">
      </button>
    </a>
  </h1>
{% endblock page_header %}

{% block content %}

  {% if owned_ingredient %}
    <div class="row row-cols-1 row-cols-md-4">
    {% for item in owned_ingredient %}
      <div class="card ml-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{ item.quantity | floatformat }} {{ ingredient.get_unit_display }} </h5>
          <p class="card-text">'Best before' date: {{ item.best_before | date:"j M Y" }}</p>
          {% if item.note != '...' %}
            <p class="card-text">note: "{{ item.note }}"</p>
          {% else %}
            <br>
          {% endif %}
          <a href="{% url 'manage_ingredients:edit_owned_ingredient' item.id %}">
            <button type="button" class="btn btn-warning btn-sm">Edit</button></a>
          <a href="{% url 'manage_ingredients:delete_owned_ingredient' item.id %}">
            <button type="button" class="btn btn-danger btn-sm">Delete</button></a>
        </div>
      </div>
    {% endfor %}
    </div>
  {% endif %}

{% endblock content %}

manage_ingredients/templates/manage_ingredients/recipes_cards.html
<div class="row row-cols-1 row-cols-md-2">
  {% for recipe in recipes %}
    <div class="col mb-4">
      <div class="card">
        <div class="card-header text-center" style="background-color: #f0fafc">
          <h5>{{ recipe.title }}</h5>
          <br>
          {% if buttons %}
            <a href="{% url 'manage_ingredients:edit_recipe' recipe.id %}">
                <button type="button" class="btn btn-sm btn-warning">Edit</button></a>
            <a href="{% url 'manage_ingredients:delete_recipe' recipe.id %}">
                <button type="button" class="btn btn-sm btn-danger">Delete</button></a>
          {% endif %}
        </div>
        <div class="card-body text-info">
          <p>Currently in your fridge and pantry:</p>
          <ul class="recipe-ingredients-list">
            {% for ingredient in recipe.ingredient.all %}
              {% if ingredient.ownedingredient_set.all %}
                <li>{{ ingredient.name }}
                  <ul>
                    {% for i in ingredient.ownedingredient_set.all %}
                      {% if i.note != '...' %}
                        <li>{{ i.quantity | floatformat}} {{ ingredient.get_unit_display }}
                          | 'best before' date: {{ i.best_before | date:"j M Y" }} | note: "{{ i.note }}"</li>
                      {% else %}
                        <li>{{ i.quantity | floatformat}} {{ ingredient.get_unit_display }}
                          | 'best before' date: {{ i.best_before | date:"j M Y" }}</li>
                      {% endif %}
                    {% endfor %}
                  </ul>
                </li>
              {% endif %}
            {% endfor %}
          </ul>
          <a href="{{ recipe.link }}" target="_blank" rel="noopener">
            <button type="button" class="btn btn-outline-info">Open this recipe &raquo;</button></a>
        </div>
        </div>
    </div>
  {% endfor %}
</div>

manage_ingredients/templates/manage_ingredients/use_up_today_cards.html
{% if objects %}
  <div class="alert alert-{{ color }} my-4" role="alert">
    {{ text }}
  </div>
  <div class="row row-cols-1 row-cols-md-3">
    {% for ingredient in objects %}
      <div class="col mb-4">
        <div class="card border-{{ color }} mb-3" style="max-width: 18rem;">
          <div class="card-header" style="background-color: #f0fafc">
            <h5>{{ ingredient.ingredient.name }}
            <a href="{% url 'manage_ingredients:edit_owned_ingredient_use_up' ingredient.id %}">
              <button type="button" class="btn btn-warning btn-sm ml-5">Edit</button></a>
            <a href="{% url 'manage_ingredients:delete_owned_ingredient_use_up' ingredient.id %}">
              <button type="button" class="btn btn-danger btn-sm">Delete</button></a>
            </h5>
            {% if ingredient.note != '...' %}
              <p>note: "{{ ingredient.note }}"</p>
            {% endif %}
          </div>
          <div class="card-body text-{{ color }}">
            <h5 class="card-title">{{ note }} {{ ingredient.best_before | date:"j M Y" }}</h5>
            <p class="card-text">
              quantity: {{ ingredient.quantity | floatformat}} {{ ingredient.ingredient.get_unit_display }}
            </p>
            <a href="{% url 'manage_ingredients:get_recipes' ingredient.ingredient.id %}">
              <button type="button" class="btn btn-outline-info">Recipes &raquo;</button>
            </a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endif %}