ingredients_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('manage_ingredients.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manage_ingredients/urls.py
from django.urls import path
from . import views


app_name = 'manage_ingredients'
urlpatterns = [
    path('', views.main, name='main'),
    path('ingredients/', views.ingredients_list, name='ingredients_list'),
    path('ingredients/<int:ingredient_id>', views.owned_ingredients, name='owned_ingredients'),
    path('ingredients/<int:ingredient_id>/add_owned_ingredient', views.add_owned_ingredient,
         {'redirect_url': 'manage_ingredients:owned_ingredients',
          'url_name': 'manage_ingredients:add_owned_ingredient_id'}, name='add_owned_ingredient_id'),
    path('recipes/', views.recipes_list, name='recipes'),
    path('use_up_today/', views.use_up_today_list, name='use_up_today'),
    path('add_ingredient/', views.add_ingredient, name='add_ingredient'),
    path('edit_ingredient/<int:ingredient_id>/', views.edit_ingredient, name='edit_ingredient'),
    path('delete_ingredient/<int:ingredient_id>/', views.delete_ingredient, name='delete_ingredient'),
    path('add_owned_ingredient/<int:ingredient_id>', views.add_owned_ingredient,
         {'redirect_url': 'manage_ingredients:ingredients_list', 'url_name': 'manage_ingredients:add_owned_ingredient'},
         name='add_owned_ingredient'),
    path('edit_owned_ingredient/<int:owned_ingredient_id>/', views.edit_owned_ingredient,
         {'redirect_url': 'manage_ingredients:owned_ingredients', 'url_name': 'manage_ingredients:edit_owned_ingredient'},
         name='edit_owned_ingredient'),
    path('delete_owned_ingredient/<int:owned_ingredient_id>/', views.delete_owned_ingredient,
         {'redirect_url': 'manage_ingredients:owned_ingredients', 'url_name': 'manage_ingredients:owned_ingredients'},
         name='delete_owned_ingredient'),
    path('use_up_today/edit_owned_ingredient/<int:owned_ingredient_id>/', views.edit_owned_ingredient,
         {'redirect_url': 'manage_ingredients:use_up_today', 'url_name': 'manage_ingredients:edit_owned_ingredient_use_up'},
         name='edit_owned_ingredient_use_up'),
    path('use_up_today/delete_owned_ingredient/<int:owned_ingredient_id>/', views.delete_owned_ingredient,
         {'redirect_url': 'manage_ingredients:use_up_today', 'url_name': 'manage_ingredients:use_up_today'},
         name='delete_owned_ingredient_use_up'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('edit_recipe/<int:recipe_id>/', views.edit_recipe, name='edit_recipe'),
    path('delete_recipe/<int:recipe_id>/', views.delete_recipe, name='delete_recipe'),
    path('get_recipes/<int:ingredient_id>/', views.get_recipes, name='get_recipes'),
    path('manage_categories/', views.manage_categories, name='manage_categories'),
    path('categories/', views.categories_list, name='categories_list'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

templates/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="eng">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='icon' href="{% static 'images/cooking_icon.png' %}">
    <title>Cooking Manager</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #f0fafc">
      <img src="{% static 'images/cooking_icon.png' %}" width="25" height="30">
      <a class="navbar-brand ml-3" href="{% url 'manage_ingredients:main' %}">CookingManager</a>
      {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'manage_ingredients:use_up_today' %}">Use up today</a>
        <a class="nav-link" href="{% url 'manage_ingredients:ingredients_list' %}">Keep track</a>
        <a class="nav-link" href="{% url 'manage_ingredients:recipes' %}">Recipes</a>
      {% endif %}

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
          </li>
        {% endif %}
      </ul>
    </div>
    </nav>

    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>
  </body>
</html>